### ISSUE TITLE
Typing ? causes Global Hotkeys modal to appear

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#148]
For some reason on WebCatalog 6.0.0 on macOS typing a ? mark into an email or tweet or anything else I'm using as a webcatalog app causes this dialog to appear.
<img width="501" alt="screen shot 2017-06-29 at 1 37 45 pm" src="https://user-images.githubusercontent.com/157270/27709250-3e3fce48-5cd0-11e7-8896-4758295b13be.png">

**Comment by quanglam2807** [comment]
@swrobel This is a leftover from the tab/workspace feature which I have removed in the final version of 6.0. I'll remove it.

**Comment by quanglam2807** [comment]
@swrobel It seems like I have already removed it in 6.0 
https://github.com/webcatalog/webcatalog/commit/bed081e29b9120de02685c68af13da42c7f2097a#diff-8bdd8c4daa03a4164e169f0098588201L246

Are you running the latest version? https://github.com/webcatalog/webcatalog/releases/tag/v6.0.0

**Comment by swrobel** [comment]
I guess this brings up a good question - when I update WebCatalog.app, do I have to quit & restart all "apps" to get them to update? I suppose I had updated it, but not restarted any of my apps. My mistake, it's fixed now.

**Comment by quanglam2807** [comment]
@swrobel I think you will need to restart all your apps. But it no longer matters as in the next release, I'm looking to have all those apps work independently. 

https://github.com/webcatalog/molecule

**Comment by swrobel** [comment]
Hm, that's an interesting concept, although it worries me because it seems that's the same way that fluid works, and every time a new fluid update comes out (granted, it's much less frequent than webcatalog is updated 😁 ) it's really annoying because every single one of my fluid apps would pop up a dialog and I'd have to download the update separately for each one, which seemed like a waste of bandwidth. Do you have a workaround for that problem?

**Comment by quanglam2807** [comment]
@swrobel My idea is to use WebCatalog as the centralized update center. So you can open WebCatalog and select "Update all". 

I understand the current approach is very resource-wise because all installed apps use a same Electron binary. The new approach would make all installed apps running with a seperate binary which is not as good. Still, I will try to ensure that when there's an update, new binary is downloaded only once and then cached to save the bandwidth (and save time, too). More than that, the new approach will significantly improve the app's stability, security & features. 

Of course, if there's a chance, I wish I could continue using the current approach. It is different from other similar apps and seems to work pretty well. But most of the issues we have with the app at the moment are related to the approach. And for me, what makes WebCatalog is not about having an unique technical mechanism but about turning a complicated concept into a consumer-friendly product. So I hope that philosophy won't change: everyone can open WebCatalog, install and update an app and everything works.

**Comment by swrobel** [comment]
That's a perfect mission. Keep up the good work!
