### ISSUE TITLE
App sizes have increased massively in 7.x

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#171]
One of the big benefits of WebCatalog vs nativefier used to be that the apps were small, around 10MB. I believe. Now my apps are ~290MB which is a huge increase. Is this intended behavior, and if so, why?

<img width="288" alt="screen shot 2017-10-29 at 11 09 09 am" src="https://user-images.githubusercontent.com/157270/32146742-9faafddc-bc99-11e7-9e48-da0f56cd8419.png">

**Comment by jnv** [comment]
Perhaps this is caused by the new [molecule](https://github.com/webcatalog/molecule) engine, which turns webpages into electron apps? The [announcement](https://medium.com/webcatalog/announcing-webcatalog-7-0-c5bafe5442a8) suggests so:

> With Molecule … WebCatalog Apps now run independently from WebCatalog. It means you can uninstall or move WebCatalog to external storage without affecting those apps.

If this is the case, WebCatalog just adds fancy GUI for nativefier-like behavior where each application carries its own copy of Electron.

**Comment by quanglam2807** [comment]
@jnv You're right. @swrobel As I explained to you before, this is intentional to improve the stability of the app.

I do agree that the app sizes are too big and the majority of the components can be shared between these apps. It is a compromise we have to live with to move the development forward. Then, when a shared Electron runtime mode is developed, this problem will be resolved completely. 

@develar WebCatalog doesn't need to deal with the installer formats' quirks so maybe you can give us a better insight?

Reference:
electron/electron#673
electron-userland/electron-builder#1942

**Comment by develar** [comment]
@quanglam2807 Shared runtime for macOS will be not supported by electron-builder any time soon. I will inspect generated app files, maybe some optimisations maybe made.

**Comment by quanglam2807** [comment]
@develar All these apps uses a same `app.asar` file. Is there a way to change its location? I can move it to a shared folder.

**Comment by quanglam2807** [comment]
I'll use symlink. It would save 50% of the app sizes.

**Comment by quanglam2807** [comment]
<img width="805" alt="screen shot 2017-11-02 at 6 26 16 pm" src="https://user-images.githubusercontent.com/1548835/32323674-6358bdc8-bffb-11e7-8bc4-98988a75b5be.png">

:)

**Comment by vlad-cotfas** [comment]
It will be nice to have more mac SSD space :D

**Comment by quanglam2807** [comment]
It's ready. Can you guys test it a little bit to make sure everything works correctly?
@cotfas @jnv @swrobel 
https://github.com/webcatalog/webcatalog/releases/tag/v7.4.0

**Comment by swrobel** [comment]
Wow, truly incredible work! No issues so far, but I will update if that changes.

Before:
<img width="406" alt="screen shot 2017-11-03 at 12 44 01 pm" src="https://user-images.githubusercontent.com/157270/32393031-3ed701ae-c095-11e7-8b75-c72d8b8b11f5.png">

After:
<img width="461" alt="screen shot 2017-11-03 at 12 46 17 pm" src="https://user-images.githubusercontent.com/157270/32393036-42e46624-c095-11e7-98ae-77d7321122d9.png">

**Comment by vlad-cotfas** [comment]
Hello Quang, it is working, thank you for this feature! You saved my SSD space 🥇
