### ISSUE TITLE
Provide PPA for WebCatalog

### ISSUE THREAD

**Issue by jlandes** [quanglam2807/appifier#222]
It would be great if WebCatalog could be provided via a PPA for Linux systems, so that installation and upgrades can be handled automatically with the APT.

**Comment by quanglam2807** [comment]
The app relies on `electron-builder` but the library doesn't support PPA. :( electron-userland/electron-builder#1170

**Comment by alfinbi** [comment]
it is easy to provide arch linux user repository so that users can add webcatalog repo to /etc/pacman.conf and update webcatalog on pacman -Syu command. it will safe much time to update rather than downloading the pacman file and manually update.

here is the [wiki](https://wiki.archlinux.org/index.php/unofficial_user_repositories#Adding_your_repository_to_this_page)

here is [example repo](http://repo.archlinuxcn.org/x86_64/)

**Comment by matrixik** [comment]
Maybe make it into Snap app and then it can be build and updated automatically.
Example for Hugo https://github.com/gohugoio/hugo/blob/master/snapcraft.yaml
More info https://snapcraft.io/

**Comment by quanglam2807** [comment]
@matrixik I did some witchcraft (https://github.com/webcatalog/webcatalog/blob/master/dist.js#L102) to make WebCatalog works so it doesn't work well with with Snap or AppImage.

#199 #219
