### ISSUE TITLE
Quit app on last window close (macOS)

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#38]
by default the app stays running if you close the last open window
(and opens new window if click its icon in dock)

but for some app it seems better if the app would quit with its last window

this would need issue #37 first thought (custom settings for app)

**Comment by quanglam2807** [comment]
@natrim I think it's better not to change it. It's a default behavior of macOS, isn't it?

**Comment by natrim** [comment]
yes its default for most apps,
 but i prefer my apps closed when i click on the close button
as i when i click it i really want the app gone until later and not take slot in my dock

anyway its just one setting more and change to 
` if (process.platform !== 'darwin') {
    app.quit();
  }` 
to something like 
`if (process.platform !== 'darwin' || settings.closeAppOnMac) {
    app.quit();
 }`
 in main.js

and the setting could be set to be hidden if not on mac

**Comment by Rediwed** [comment]
@quanglam2807 Please DO NOT change this behaviour. macOS's power comes from it's universal behaviour in different applications (e.g. even though you've never used a certain app before you will already know how it works due to the design & behavioural language).

Or make a a opt-out thing.. I wouldn't want spotify to quit when i close the last window, I'd want it to continue playing music without a GUI.

**Comment by quanglam2807** [comment]
@Rediwed @natrim it won't be turned on by default. So everyone is happy. :)
