### ISSUE TITLE
Add back WidevineCDM (Netflix)

### ISSUE THREAD

**Issue by pierrenel** [quanglam2807/appifier#73]
Ummmm what happened to Netflix? 🤔

**Comment by quanglam2807** [comment]
#71 @pierrenel @jjnilton Now, WidevineCDM plugin which is required to run Netflix, is removed. This is because the technology is not open-source and it takes a lot of time to keep updating the plugin manually.

Removing it allows the plugin allows me to keep development forward. But I'll keep this issue open because as soon as I figure out a way to automate the process, I'll bring it back.

**Comment by quanglam2807** [comment]
https://github.com/webcatalog/electron-widevinecdm I'm working to bring it back :)
